- hosts: all
  become: false
  tasks: https://github.com/Anil-Tamadaddi/kubernet_ansible/blob/master/ansible.yml
     - name: delete old deployment
       command: kubectl delete -f /home/ubuntu/Deployment.yml
     - name: delete old service
       command: kubectl delete -f /home/ubuntu/Service.yml
     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/ubuntu/Service.yml
